name: Release
on:
  push:
    branches:
    - main
    - release/*
  create:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@master

      - name: Build Linux amd64 binary
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)_linux_amd64 -a -ldflags '-s -w' .

      - name: Build Linux arm64 binary
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)_linux_arm64 -a -ldflags '-s -w' .

      - name: Install olsu
        run: wget https://github.com/Telling/olsu/releases/download/v0.1.0/olsu-linux-amd64.zip && unzip olsu-linux-amd64.zip && chmod +x olsu-linux-amd64 && pwd && ls -la
        
      - name: Create or update release
        env:
          OLSU_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLSU_DELETE_RELEASE: yes
        run: ./olsu-linux-amd64 -o $(echo $GITHUB_REPOSITORY | cut -d "/" -f 1) -r $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2) "Latest release" "latest" "Automatic release" $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)_linux_amd64 $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)_linux_arm64
